### ISSUE TITLE
Issue with straddles in cash games

### ISSUE THREAD

**Issue by zerocoupon** [valakuzhyk/pokernow_club_stats#3]
Hi,

looks like there is some issue with straddles, have you encountered the same?

Started hand dealer: player1 @ E1g4VDiOqu
Unexpected line found in log. Likely the log format has changed and this script needs to be updated.
"player1 @ E1g4VDiOqu" posts a straddle of 8
['"player1 @ E1g4VDiOqu" posts a straddle of 8', '2021-01-30T20:02:05.008Z', '161203692502410']
Traceback (most recent call last):
  File "/Users/c/Documents/pn_stats/log_processor.py", line 409, in <module>
    main()
  File "/Users/c/Documents/pn_stats/log_processor.py", line 404, in main
    evening = p.parse("", filename)
  File "/Users/c/Documents/pn_stats/log_processor.py", line 226, in parse
    raise e
  File "/Users/c/Documents/pn_stats/log_processor.py", line 223, in parse
    self.parse_line(row)
  File "/Users/c/Documents/pn_stats/log_processor.py", line 387, in parse_line
    assert False
AssertionError

**Comment by valakuzhyk** [comment]
Hi there noodlejo,

I don't believe I ever implemented support for straddles. Do you mind posting a log (or portion of a log containing the straddle) from a game containing straddles? That will speed up the fixing process.

**Comment by zerocoupon** [comment]
Hi! See log below. Newbie at python/github here so bear with me ;)

Edit: Like your work btw!

[poker_now_log_5Y7jDjDPKnEJoiJm2YrssyLgO.txt](https://github.com/valakuzhyk/pokernow_club_stats/files/5917756/poker_now_log_5Y7jDjDPKnEJoiJm2YrssyLgO.txt)

**Comment by valakuzhyk** [comment]
No worries on being new, happy to see that you gave this code a try.
I just pushed some changes that should allow computing some stats for your game. Let me know whether it worked or not.

**Comment by zerocoupon** [comment]
Great work! Thanks, it did the trick. I will now try to create a chart for net profits, i.e. stack adjusted for buy ins.

**Comment by valakuzhyk** [comment]
I look forward to any code contributions! Feel free to file another issue if you have any more issues.
