### ISSUE TITLE
Log File Format Has Changed

### ISSUE THREAD

**Issue by gargnim** [valakuzhyk/pokernow_club_stats#7]
**Describe the bug**
The log format has changed and script needs to be updated. I can fix this.

**Logfile**
**WARNING**: Unexpected line found in log. Likely the log format has changed and this script needs to be updated.
The player "Belgianboy @ 9x5lNdtEOr" is in the tournament with a stack of 1000.
['The player "Belgianboy @ 9x5lNdtEOr" is in the tournament with a stack of 1000.', '2021-05-09T23:40:36.994Z', '162060364235500']

**Comment by valakuzhyk** [comment]
Would appreciate any contributions you wish to make.

**Comment by WilsonBreton5** [comment]
any progress at updating it?

**Comment by valakuzhyk** [comment]
If I don't get a pull request by this weekend, I can spend a couple hours updating if I can get an example log file using the new format. @WilsonBreton5 @gargnim

**Comment by WilsonBreton5** [comment]
[poker_now_log_HRzYd18uNZMyBff9hMBkRXorg.csv](https://github.com/valakuzhyk/pokernow_club_stats/files/6519379/poker_now_log_HRzYd18uNZMyBff9hMBkRXorg.csv)
[poker_now_log_h-AyONy--TvoFi40rJ6xlEE16.csv](https://github.com/valakuzhyk/pokernow_club_stats/files/6519380/poker_now_log_h-AyONy--TvoFi40rJ6xlEE16.csv)



heres two logs from my previous games

**Comment by valakuzhyk** [comment]
@WilsonBreton5, I addressed the lines in your logs so yours should work with the latest version.

@gargnim I added a new flag (--ignore_warnings) that should allow your log to finish. If the new lines are critical to computing the stats, then please reopen the issue/open a new issue and include your logs that aren't working.
